# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
workflows:
  my-workflow:
    jobs:
      - build :
          context:
            - DOCKERHUB
          filters:
            branches:
              only: master
            tags:
              only: /^v[0-9]+(\.[0-9]\.[0-9])*$/

jobs:
  build:
    environment:
      IMAGE_NAME: unflag/quote-telegram-bot
      VERSION: << pipeline.git.tag >>
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.16.0
    steps:
      - checkout
          post:
            - git fetch --tags && git tag
      - setup_remote_docker
      - run:
          name: Install Dependencies
          command: go mod download
      - run:
          name: Build binary
          command: make
      - run:
          name: Build docker image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Push docker image
          command: |
            docker login -u unflag -p $DOCKERHUB_PASSWORD
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$VERSION
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$VERSION
